// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQ-iEeS4NygJZmb90TiY0bAlWnMpYnoE',
    appId: '1:920111927921:web:e16315135e390bfb8841d0',
    messagingSenderId: '920111927921',
    projectId: 'login-8e90e',
    authDomain: 'login-8e90e.firebaseapp.com',
    storageBucket: 'login-8e90e.appspot.com',
    measurementId: 'G-6YHPV8F29P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxc8BG4XjU1Oxodzi-RWI5Yx1pU4sGLEk',
    appId: '1:920111927921:android:977095eb5cefac5e8841d0',
    messagingSenderId: '920111927921',
    projectId: 'login-8e90e',
    storageBucket: 'login-8e90e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtD3HWxRdtaCD5wIwU2zZpTUOB1HDmVo',
    appId: '1:920111927921:ios:b7c45f6ab1d59cca8841d0',
    messagingSenderId: '920111927921',
    projectId: 'login-8e90e',
    storageBucket: 'login-8e90e.appspot.com',
    iosClientId: '920111927921-3qj132c233beh6as5up4sn1bi51pp1h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtD3HWxRdtaCD5wIwU2zZpTUOB1HDmVo',
    appId: '1:920111927921:ios:b7c45f6ab1d59cca8841d0',
    messagingSenderId: '920111927921',
    projectId: 'login-8e90e',
    storageBucket: 'login-8e90e.appspot.com',
    iosClientId: '920111927921-3qj132c233beh6as5up4sn1bi51pp1h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
